AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a CloudFront distribution

Parameters:
  S3BucketOrigin:
    Description: The S3 bucket name to use as the CloudFront origin
    Type: String
    Default: 'my-unique-bucket-nm' # Example bucket name for demo purposes

Resources:
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties: 
      DistributionConfig: 
        Enabled: true
        Origins: 
          - Id: !Sub '${S3BucketOrigin}-origin'
            DomainName: !Sub '${S3BucketOrigin}.s3.amazonaws.com'
            S3OriginConfig: 
              OriginAccessIdentity: '' # Optional: Use if you have an Origin Access Identity set up
        DefaultCacheBehavior: 
          TargetOriginId: !Sub '${S3BucketOrigin}-origin'
          ViewerProtocolPolicy: 'redirect-to-https'
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          ForwardedValues: 
            QueryString: false
            Cookies: 
              Forward: 'none'
          MinTTL: 0
          DefaultTTL: 86400 # Default TTL in seconds (1 day)
          MaxTTL: 31536000 # Max TTL in seconds (1 year)
        ViewerCertificate: 
          CloudFrontDefaultCertificate: true # Optional: Use if you don't have a custom SSL certificate
        PriceClass: PriceClass_100 # Optional: Use PriceClass_200 or PriceClass_All for wider distributions
        Comment: !Sub 'CloudFront distribution for ${S3BucketOrigin}' # Optional: Comment for the distribution

Outputs:
  CloudFrontDistributionId:
    Description: The ID of the CloudFront distribution
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: The domain name of the CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
